# Generated by Django 3.2.14 on 2022-10-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plinic", "0016_alter_playlist_title"),
        ("accounts", "0007_alter_profile_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="favorite_genres", to="plinic.Genre"
            ),
        ),
    ]
