# Generated by Django 3.2.14 on 2022-10-27 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plinic", "0016_alter_playlist_title"),
        ("accounts", "0008_profile_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="genres",
            field=models.ManyToManyField(blank=True, to="plinic.Genre"),
        ),
    ]
