# Generated by Django 3.2.14 on 2022-10-20 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plinic", "0014_auto_20220927_0037"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=10),
        ),
    ]
