# Generated by Django 3.2.14 on 2022-10-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plinic", "0015_auto_20221020_0829"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playlist",
            name="title",
            field=models.CharField(max_length=30),
        ),
    ]
