# Generated by Django 3.2.14 on 2022-07-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_pic'),
        ('plinic', '0004_alter_post_voter_set'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='scrapper_set',
            field=models.ManyToManyField(blank=True, related_name='playlist_scrapper_set', to='accounts.Profile'),
        ),
    ]
