# Generated by Django 3.2.14 on 2022-09-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plinic', '0010_alter_track_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='duration',
            field=models.DateTimeField(),
        ),
    ]
