# Generated by Django 3.2.14 on 2022-09-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plinic', '0012_alter_track_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(default='tempList', max_length=150),
        ),
    ]
